services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: swift_webapp
    ports:
      - "8080:8080"
    volumes:
      - ..:/workspaces:cached
    working_dir: /workspaces
    command: sleep infinity
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: kakakakakku/mysql-world-database:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: swift_webapp
    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
